import test from 'node:test';
import assert from 'node:assert/strict';
import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { adaptFirestore } from '../lib/platform/firestore-adapter';
import { grantCredits, reserveCredits, settleCredits } from '../lib/credits/ledger';
import { startAttempt, challenge, decideAttempt, completeAttempt, refreshGrant, verifyAccess } from '../lib/auth/client-grants';
import { prepare, invoke, reconcileRequest } from '../lib/inference/engine';
import { ModelPolicy, InferenceInput, Provider } from '../lib/inference/types';
const projectId = 'demo-swahilipro';
// Refuse to fall back to a live service. This suite never accepts production config.
assert.ok(process.env.FIRESTORE_EMULATOR_HOST, 'Firestore emulator required');
const db = getFirestore(initializeApp({ projectId }, 'ledger-integration'));
const store = adaptFirestore(db);
test('real Firestore serializes competing wallet writes and settles exactly once', async () => {
  const uid = `test-${Date.now()}`;
  await grantCredits(store, uid, 100, 'grant_key_00000001', 'test-admin', 'Emulator beta');
  const rows = await Promise.allSettled(['request_key_000001', 'request_key_000002'].map((key) => reserveCredits(store, uid, 75, key, 'a'.repeat(64))));
  const winner = rows.find((r) => r.status === 'fulfilled');
  assert.equal(rows.filter((r) => r.status === 'fulfilled').length, 1);
  assert.ok(winner && winner.status === 'fulfilled');
  await Promise.all([settleCredits(store, uid, winner.value.id, 30), settleCredits(store, uid, winner.value.id, 30)]);
  assert.deepEqual((await db.doc(`creditAccounts/${uid}`).get()).data(), { balance: 70, reserved: 0 });
});
test('real Firestore consumes approved attempt once and commits refresh-reuse revocation', async () => {
  const now = Date.now(), verifier = 'v'.repeat(64);
  const attempt = await startAttempt(store, { clientType: 'cli', label: 'Emulator terminal', challenge: challenge(verifier) }, now);
  await decideAttempt(store, attempt.attemptId, 'emulator-alice', true, attempt.confirmationCode, now + 1);
  const rows = await Promise.allSettled([1, 2].map(() => completeAttempt(store, attempt.attemptId, attempt.pollingSecret, verifier, now + 2)));
  const winner = rows.find((r) => r.status === 'fulfilled');
  assert.equal(rows.filter((r) => r.status === 'fulfilled').length, 1);
  assert.ok(winner && winner.status === 'fulfilled');
  const next = await refreshGrant(store, winner.value.refreshToken, now + 3);
  await assert.rejects(refreshGrant(store, winner.value.refreshToken, now + 4), /refresh_reused/);
  await assert.rejects(verifyAccess(store, next.accessToken, now + 5), /authorization_revoked/);
});
test('Firestore client API cannot read or write a financial document', async () => {
  const host = process.env.FIRESTORE_EMULATOR_HOST!;
  const url = `http://${host}/v1/projects/${projectId}/databases/(default)/documents/creditAccounts/forbidden`;
  const read = await fetch(url);
  assert.equal(read.status, 403);
  const write = await fetch(url, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fields: { balance: { integerValue: '99999' } } }) });
  assert.equal(write.status, 403);
});
test('real Firestore claims paid invocation once and reconciles confirmed usage', async () => {
  const uid = `inference-${Date.now()}`;
  const policy: ModelPolicy = { id: 'fake', name: 'Fake', region: 'us-east-1', api: 'converse', billingVerified: true, inputMicrocreditsPerToken: 2, outputMicrocreditsPerToken: 3, maxInputTokens: 100, maxOutputTokens: 10 };
  const input: InferenceInput = { model: 'fake', messages: [{ role: 'user', content: 'Hello' }], maxOutputTokens: 10 };
  let calls = 0;
  const provider: Provider = { count: async () => 5, async *stream() { calls++; yield { type: 'usage', inputTokens: 5, outputTokens: 2 }; } };
  await grantCredits(store, uid, 1000, 'grant_key_00000001', 'admin', 'Emulator');
  const rows = await Promise.all([1, 2].map(() => prepare(store, provider, uid, null, 'request_key_000001', input, policy, 100000, new AbortController().signal)));
  assert.equal(rows.filter((row) => !row.duplicate).length, 1);
  const invoked = await Promise.allSettled(rows.map((row) => invoke(store, provider, uid, row.id, input, policy, new AbortController().signal, () => {})));
  assert.equal(invoked.filter((row) => row.status === 'fulfilled').length, 1);
  assert.equal(calls, 1);
  assert.deepEqual((await db.doc(`creditAccounts/${uid}`).get()).data(), { balance: 984, reserved: 0, activeRequests: 0 });
  const next = await prepare(store, provider, uid, null, 'request_key_000002', input, policy, 100000, new AbortController().signal);
  await db.doc(`inferenceRequests/${next.id}`).update({ state: 'invoking', confirmedActual: 16 });
  assert.equal(await reconcileRequest(store, next.id), 'settled');
  assert.equal((await db.doc(`creditAccounts/${uid}`).get()).data()!.balance, 968);
});
test.after(async () => { await db.terminate(); });
