import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useAuth, UserButton } from "@clerk/nextjs";
import { RedirectToSignIn } from "@clerk/nextjs";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Swahilipro",
  description: "Generated by Boniface Masota",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const { isSignedIn } = useAuth();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Conditionally render content based on authentication status */}
        {isSignedIn ? (
          <div>
            <div className="absolute top-4 right-4">
              <UserButton />
            </div>
            {children}
          </div>
        ) : (
          <RedirectToSignIn />
        )}
      </body>
    </html>
  );
}
